name: CI - Builder (jsonjsdb-builder)

on:
  push:
    branches: [main]
    paths:
      - 'jsonjsdb-builder/**'
      - '.github/workflows/ci-builder.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'eslint.config.ts'
      - '!**/*.md'
  pull_request:
    branches: [main]
    paths:
      - 'jsonjsdb-builder/**'
      - '.github/workflows/ci-builder.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'eslint.config.ts'
      - '!**/*.md'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        working-directory: jsonjsdb-builder
        run: npm run lint

      - name: Run tests
        working-directory: jsonjsdb-builder
        run: npm run test

      - name: Build package
        working-directory: jsonjsdb-builder
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jsonjsdb-builder-dist
          path: jsonjsdb-builder/dist/
          retention-days: 7

      - name: Check package integrity
        working-directory: jsonjsdb-builder
        run: npm pack --dry-run
